#!/bin/bash

mkdir "Demon's Souls (USA)"
cd "Demon's Souls (USA)"
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_DISC.SFB

mkdir PS3_Game
cd PS3_Game
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/PS3LOGO.DAT
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/PIC1.PNG
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/PARAM.SFO
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/ICON1.PAM
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/ICON0.PNG

mkdir TROPDIR
cd TROPDIR
mkdir NPWR00881_00
cd NPWR00881_00
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/TROPDIR/NPWR00881_00/TROPHY.TRP
cd ..
cd ..

mkdir USRDIR
cd USRDIR
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part01.exe
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part02.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part03.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part04.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part05.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part06.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part07.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part08.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part09.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part10.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part11.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part12.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part13.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part14.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part15.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part16.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part17.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part18.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part19.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part20.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part21.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part22.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part23.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part24.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part25.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part26.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part27.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part28.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part29.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part30.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part31.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part32.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part33.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part34.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part35.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part36.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part37.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part38.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part39.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part40.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part41.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part42.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part43.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part44.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part45.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part46.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part47.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part48.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part49.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part50.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part51.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part52.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part53.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part54.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part55.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part56.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part57.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part58.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part59.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part60.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part61.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part62.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part63.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part64.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part65.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/USRDIR-01/USRDIR-01.part66.rar


mkdir map
cd map
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part01.exe
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part02.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part03.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part04.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part05.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part06.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part07.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part08.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part09.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part10.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part11.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part12.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part13.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part14.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part15.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part16.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part17.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part18.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part19.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part20.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part21.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part22.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part23.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part24.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part25.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part26.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part27.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part28.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part29.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part30.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part31.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part32.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part33.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part34.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part35.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part36.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part37.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part38.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part39.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part40.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part41.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part42.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part43.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part44.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part45.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part46.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part47.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part48.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part49.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part50.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part51.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part52.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part53.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part54.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part55.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part56.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part57.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part58.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part59.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part60.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part61.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part62.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part63.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part64.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part65.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part66.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part67.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part68.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part69.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part70.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part71.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part72.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part73.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part74.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part75.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part76.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part77.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part78.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part79.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part80.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part81.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part82.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part83.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part84.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part85.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/map/map.part86.rar
cd ..

mkdir movie
cd movie
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part01.exe
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part02.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part03.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part04.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part05.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part06.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part07.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part08.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part09.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part10.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part11.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part12.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part13.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part14.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part15.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part16.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part17.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part18.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part19.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part20.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part21.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part22.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part23.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part24.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part25.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part26.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part27.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part28.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part29.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part30.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part31.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part32.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part33.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part34.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part35.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part36.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part37.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part38.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part39.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part40.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part41.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part42.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part43.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part44.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part45.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part46.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part47.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part48.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part49.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part50.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part51.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part52.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part53.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part54.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part55.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part56.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part57.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part58.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part59.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part60.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part61.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part62.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part63.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part64.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part65.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part66.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part67.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part68.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part69.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part70.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part71.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part72.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part73.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part74.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part75.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part76.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part77.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part78.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part79.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part80.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part81.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part82.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part83.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part84.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part85.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part86.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part87.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part88.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part89.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part90.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part91.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part92.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part93.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part94.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part95.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part96.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part97.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part98.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part99.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part100.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part101.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part102.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part103.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part104.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part105.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/movie/movie.part106.rar
cd ..

mkdir obj
cd obj
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part01.exe
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part02.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part03.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part04.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part05.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part06.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part07.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part08.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part09.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part10.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part11.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part12.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part13.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part14.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part15.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part16.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part17.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part18.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part19.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part20.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part21.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part22.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part23.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part24.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part25.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part26.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part27.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part28.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part29.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part30.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part31.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part32.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part33.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part34.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part35.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part36.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part37.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part38.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part39.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part40.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part41.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part42.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part43.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part44.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part45.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part46.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part47.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part48.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/obj/obj.part49.rar
cd ..

mkdir parts
cd parts
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/parts/parts.part01.exe
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/parts/parts.part02.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/parts/parts.part03.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/parts/parts.part04.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/parts/parts.part05.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/parts/parts.part06.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/parts/parts.part07.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/parts/parts.part08.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/parts/parts.part09.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/parts/parts.part10.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/parts/parts.part11.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/parts/parts.part12.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/parts/parts.part13.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/parts/parts.part14.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/parts/parts.part15.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/parts/parts.part16.rar
wget https://github.com/brissonsean/Backup_Games/raw/Dem0nS0uls-Ps3/Demon's%20Souls%20(USA)/PS3_GAME/USRDIR/parts/parts.part17.rar
cd ..
